const marvel_heros =[ "thor", "ironman","spiderman"]
const dc_heros = [ " superman","flash","batman"]

//marvel_heros.push(dc_heros);

//console.log(marvel_heros);
//console.log(marvel_heros[3][1]);

//const allheros = marvel_heros.concat(dc_heros)
//console.log(allheros);
const all_new_heros =[  marvel_heros,dc_heros]

console.log(all_new_heros);


const ptb=[1,2,3,4,5,6,[4,5,6,7,6],6,4,5,7[5,6]]
const ind=ptb.flat(Infinity)
console.log(ind)

const pak = rdytfdyfufufc;
cosole.log(Array.from("pak"))